import {
  clients,
  deliverableMeals,
  deliveryRequests,
  depots,
  driverSessions,
  ingredientItems,
  intakeDrafts,
  intakeMessages,
  routeStopMealItems,
  routeStops,
  routes,
  vehicles,
  volunteerAvailability,
  volunteers,
} from "@/server/db/schema";

type NewClient = typeof clients.$inferInsert;
type NewDeliverableMeal = typeof deliverableMeals.$inferInsert;
type NewDeliveryRequest = typeof deliveryRequests.$inferInsert;
type NewDepot = typeof depots.$inferInsert;
type NewDriverSession = typeof driverSessions.$inferInsert;
type NewIngredientItem = typeof ingredientItems.$inferInsert;
type NewIntakeDraft = typeof intakeDrafts.$inferInsert;
type NewIntakeMessage = typeof intakeMessages.$inferInsert;
type NewRoute = typeof routes.$inferInsert;
type NewRouteStop = typeof routeStops.$inferInsert;
type NewRouteStopMealItem = typeof routeStopMealItems.$inferInsert;
type NewVehicle = typeof vehicles.$inferInsert;
type NewVolunteer = typeof volunteers.$inferInsert;
type NewVolunteerAvailability = typeof volunteerAvailability.$inferInsert;

const SEED_NOW = new Date("2026-04-23T12:18:00-07:00");
const TODAY = "2026-04-23";
const TOMORROW = "2026-04-24";
const LATER = "2026-04-26";

const day = (value: string) => value;
const stamp = (value: string) => new Date(value);

const addMinutes = (value: Date, minutes: number) =>
  new Date(value.getTime() + minutes * 60_000);

const sharedCreatedAt = stamp("2026-04-22T08:00:00-07:00");

type HouseholdSeed = {
  id: string;
  firstName: string;
  lastName: string;
  preferredName?: string;
  phone?: string;
  municipality: string;
  neighborhood: string;
  addressLine1: string;
  postalCode: string;
  latitude: number;
  longitude: number;
  householdSize: number;
  dietaryTags: string[];
  allergenFlags: string[];
  accessNotes?: string;
  safeToLeave?: boolean;
  doNotEnter?: boolean;
  assistanceAtDoor?: boolean;
  requiresTwoPerson?: boolean;
  usesWheelchair?: boolean;
  notes?: string;
  request: {
    id: string;
    requestKind: "meal_delivery" | "grocery_hamper";
    dueBucket: "today" | "tomorrow" | "later";
    scheduledDate: string;
    urgencyScore: number;
    priorityLabel: "low" | "normal" | "high" | "critical";
    requestedMealCount: number;
    approvedMealCount: number;
    coldChainRequired: boolean;
    status: "approved" | "held" | "assigned" | "out_for_delivery" | "delivered";
    routingHoldReason?: string;
    routeId?: string;
    assignedStopSequence?: number;
    approvedAt: Date;
    originalMessageExcerpt: string;
    notes?: string;
    mealPlan: Array<{ mealId: string; quantity: number }>;
    eta?: Date;
    stopStatus?: "planned" | "ready" | "delivered";
    stopNotes?: string;
  };
};

const householdSeeds: HouseholdSeed[] = [
  {
    id: "client-mabel-hart",
    firstName: "Mabel",
    lastName: "Hart",
    phone: "(250) 555-0101",
    municipality: "Victoria",
    neighborhood: "Fernwood",
    addressLine1: "1312 Gladstone Ave",
    postalCode: "V8T 1G5",
    latitude: 48.4275,
    longitude: -123.3522,
    householdSize: 1,
    dietaryTags: ["low_sodium"],
    allergenFlags: [],
    accessNotes: "Buzz suite 204 and wait for the slower elevator.",
    assistanceAtDoor: true,
    notes: "Neighbour appreciates a quick call from the lobby.",
    request: {
      id: "request-mabel-hart",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 94,
      priorityLabel: "high",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "delivered",
      routeId: "route-victoria-core",
      assignedStopSequence: 1,
      approvedAt: stamp("2026-04-23T08:12:00-07:00"),
      eta: stamp("2026-04-23T11:58:00-07:00"),
      stopStatus: "delivered",
      originalMessageExcerpt:
        "Two chilled lunch trays would help a lot today. Please buzz and give me a minute to get to the door.",
      notes: "Call before buzzer if the lobby door sticks again.",
      mealPlan: [
        { mealId: "meal-roast-chicken", quantity: 1 },
        { mealId: "meal-vegetable-soup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-noel-okafor",
    firstName: "Noel",
    lastName: "Okafor",
    phone: "(250) 555-0102",
    municipality: "Victoria",
    neighborhood: "North Park",
    addressLine1: "901 Caledonia Ave",
    postalCode: "V8T 1E9",
    latitude: 48.4309,
    longitude: -123.3624,
    householdSize: 2,
    dietaryTags: ["soft_food"],
    allergenFlags: ["peanut"],
    accessNotes: "Text before arrival because the intercom cuts out.",
    assistanceAtDoor: true,
    request: {
      id: "request-noel-okafor",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 89,
      priorityLabel: "high",
      requestedMealCount: 3,
      approvedMealCount: 3,
      coldChainRequired: false,
      status: "out_for_delivery",
      routeId: "route-victoria-core",
      assignedStopSequence: 2,
      approvedAt: stamp("2026-04-23T08:28:00-07:00"),
      eta: stamp("2026-04-23T12:28:00-07:00"),
      stopStatus: "ready",
      originalMessageExcerpt:
        "Soft meals are still the easiest to manage. Text first because the call box is hit and miss.",
      mealPlan: [
        { mealId: "meal-soft-pasta-bake", quantity: 2 },
        { mealId: "meal-ginger-pear-cup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-lian-mercer",
    firstName: "Lian",
    lastName: "Mercer",
    preferredName: "Lian",
    phone: "(250) 555-0103",
    municipality: "Victoria",
    neighborhood: "James Bay",
    addressLine1: "408 Simcoe St",
    postalCode: "V8V 1L1",
    latitude: 48.4167,
    longitude: -123.3727,
    householdSize: 1,
    dietaryTags: ["gluten_free"],
    allergenFlags: [],
    accessNotes: "Side ramp entrance faces the alley.",
    safeToLeave: true,
    assistanceAtDoor: true,
    request: {
      id: "request-lian-mercer",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 76,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "out_for_delivery",
      routeId: "route-victoria-core",
      assignedStopSequence: 3,
      approvedAt: stamp("2026-04-23T08:41:00-07:00"),
      eta: stamp("2026-04-23T12:46:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "The side ramp is easiest. Gluten-free please, and it can be left in the cooler bag if I'm in the courtyard.",
      mealPlan: [
        { mealId: "meal-salmon-rice", quantity: 1 },
        { mealId: "meal-vegetable-curry", quantity: 1 },
      ],
    },
  },
  {
    id: "client-priya-sandhu",
    firstName: "Priya",
    lastName: "Sandhu",
    phone: "(250) 555-0104",
    municipality: "Esquimalt",
    neighborhood: "Town Centre",
    addressLine1: "876 Esquimalt Rd",
    postalCode: "V9A 3N8",
    latitude: 48.4319,
    longitude: -123.4057,
    householdSize: 3,
    dietaryTags: ["vegetarian"],
    allergenFlags: [],
    accessNotes: "Ring unit 5, then use the left-hand gate.",
    assistanceAtDoor: true,
    request: {
      id: "request-priya-sandhu",
      requestKind: "grocery_hamper",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 88,
      priorityLabel: "high",
      requestedMealCount: 3,
      approvedMealCount: 3,
      coldChainRequired: false,
      status: "delivered",
      routeId: "route-esquimalt-loop",
      assignedStopSequence: 1,
      approvedAt: stamp("2026-04-23T08:06:00-07:00"),
      eta: stamp("2026-04-23T11:41:00-07:00"),
      stopStatus: "delivered",
      originalMessageExcerpt:
        "A hamper with rice, soup, and easy fruit would cover us for the weekend. Please use the gate by the mural.",
      mealPlan: [
        { mealId: "meal-produce-hamper", quantity: 1 },
        { mealId: "meal-lentil-soup", quantity: 2 },
      ],
    },
  },
  {
    id: "client-arthur-kim",
    firstName: "Arthur",
    lastName: "Kim",
    phone: "(250) 555-0105",
    municipality: "Esquimalt",
    neighborhood: "Gorge Vale",
    addressLine1: "520 Admirals Rd",
    postalCode: "V9A 2N7",
    latitude: 48.4385,
    longitude: -123.4161,
    householdSize: 1,
    dietaryTags: ["heart_healthy"],
    allergenFlags: ["shellfish"],
    accessNotes: "Neighbour in 2B can open the main door if needed.",
    request: {
      id: "request-arthur-kim",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 84,
      priorityLabel: "high",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "out_for_delivery",
      routeId: "route-esquimalt-loop",
      assignedStopSequence: 2,
      approvedAt: stamp("2026-04-23T08:31:00-07:00"),
      eta: stamp("2026-04-23T12:17:00-07:00"),
      stopStatus: "ready",
      originalMessageExcerpt:
        "Heart-healthy trays are best. I can't manage shellfish and need chilled items kept upright.",
      mealPlan: [
        { mealId: "meal-roast-chicken", quantity: 1 },
        { mealId: "meal-yogurt-breakfast", quantity: 1 },
      ],
    },
  },
  {
    id: "client-eileen-fraser",
    firstName: "Eileen",
    lastName: "Fraser",
    phone: "(250) 555-0106",
    municipality: "Victoria",
    neighborhood: "Vic West",
    addressLine1: "150 Wilson St",
    postalCode: "V9A 7N5",
    latitude: 48.428,
    longitude: -123.3867,
    householdSize: 2,
    dietaryTags: ["low_sodium"],
    allergenFlags: [],
    accessNotes: "Leave at the blue bench if the support worker is delayed.",
    safeToLeave: true,
    request: {
      id: "request-eileen-fraser",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 73,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "out_for_delivery",
      routeId: "route-esquimalt-loop",
      assignedStopSequence: 3,
      approvedAt: stamp("2026-04-23T08:47:00-07:00"),
      eta: stamp("2026-04-23T12:39:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Two lower-sodium meals please. The bench by the courtyard gate is okay if my worker is running behind.",
      mealPlan: [
        { mealId: "meal-turkey-dinner", quantity: 1 },
        { mealId: "meal-vegetable-soup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-june-watanabe",
    firstName: "June",
    lastName: "Watanabe",
    phone: "(250) 555-0107",
    municipality: "Oak Bay",
    neighborhood: "North Oak Bay",
    addressLine1: "2207 Oak Bay Ave",
    postalCode: "V8R 1G4",
    latitude: 48.4285,
    longitude: -123.3145,
    householdSize: 1,
    dietaryTags: ["dairy_free"],
    allergenFlags: [],
    accessNotes: "Side door beside the hydrangeas is easiest.",
    assistanceAtDoor: true,
    request: {
      id: "request-june-watanabe",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 68,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-oak-bay-support",
      assignedStopSequence: 1,
      approvedAt: stamp("2026-04-23T09:02:00-07:00"),
      eta: stamp("2026-04-23T13:12:00-07:00"),
      stopStatus: "ready",
      originalMessageExcerpt:
        "Dairy-free if possible, and the side door is easier to reach than the front step.",
      mealPlan: [
        { mealId: "meal-vegetable-curry", quantity: 1 },
        { mealId: "meal-ginger-chicken-rice", quantity: 1 },
      ],
    },
  },
  {
    id: "client-hassan-baird",
    firstName: "Hassan",
    lastName: "Baird",
    phone: "(250) 555-0108",
    municipality: "Oak Bay",
    neighborhood: "South Jubilee",
    addressLine1: "1776 Fort St",
    postalCode: "V8R 1H2",
    latitude: 48.4276,
    longitude: -123.3335,
    householdSize: 2,
    dietaryTags: ["halal"],
    allergenFlags: ["egg"],
    accessNotes: "Please avoid the back stairs.",
    assistanceAtDoor: true,
    request: {
      id: "request-hassan-baird",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 71,
      priorityLabel: "normal",
      requestedMealCount: 3,
      approvedMealCount: 3,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-oak-bay-support",
      assignedStopSequence: 2,
      approvedAt: stamp("2026-04-23T09:14:00-07:00"),
      eta: stamp("2026-04-23T13:31:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Halal meals are needed for three people and the back staircase isn't safe to use anymore.",
      mealPlan: [
        { mealId: "meal-ginger-chicken-rice", quantity: 2 },
        { mealId: "meal-fruit-box", quantity: 1 },
      ],
    },
  },
  {
    id: "client-nora-leduc",
    firstName: "Nora",
    lastName: "Leduc",
    phone: "(250) 555-0109",
    municipality: "Sidney",
    neighborhood: "Town Centre",
    addressLine1: "2457 Beacon Ave",
    postalCode: "V8L 1X7",
    latitude: 48.6482,
    longitude: -123.3994,
    householdSize: 1,
    dietaryTags: ["diabetic_friendly"],
    allergenFlags: [],
    accessNotes: "Call from the curb; the lobby door has a hard pull.",
    assistanceAtDoor: true,
    request: {
      id: "request-nora-leduc",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 79,
      priorityLabel: "high",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 1,
      approvedAt: stamp("2026-04-23T09:06:00-07:00"),
      eta: stamp("2026-04-23T14:05:00-07:00"),
      stopStatus: "ready",
      originalMessageExcerpt:
        "Diabetic-friendly meals are best and the lobby door takes a hard pull.",
      mealPlan: [
        { mealId: "meal-roast-chicken", quantity: 1 },
        { mealId: "meal-yogurt-breakfast", quantity: 1 },
      ],
    },
  },
  {
    id: "client-victor-salcedo",
    firstName: "Victor",
    lastName: "Salcedo",
    phone: "(250) 555-0110",
    municipality: "Colwood",
    neighborhood: "Wishart",
    addressLine1: "3330 Wishart Rd",
    postalCode: "V9C 1R1",
    latitude: 48.4289,
    longitude: -123.4928,
    householdSize: 3,
    dietaryTags: ["vegetarian"],
    allergenFlags: ["tree_nut"],
    accessNotes: "Please use the front ramp, not the gravel side path.",
    assistanceAtDoor: true,
    request: {
      id: "request-victor-salcedo",
      requestKind: "grocery_hamper",
      dueBucket: "later",
      scheduledDate: LATER,
      urgencyScore: 67,
      priorityLabel: "normal",
      requestedMealCount: 4,
      approvedMealCount: 4,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-west-shore-link",
      assignedStopSequence: 1,
      approvedAt: stamp("2026-04-23T09:22:00-07:00"),
      eta: stamp("2026-04-26T11:54:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "A vegetarian hamper would help us cover the weekend. Please use the ramp at the front.",
      mealPlan: [
        { mealId: "meal-produce-hamper", quantity: 12 },
        { mealId: "meal-lentil-soup", quantity: 3 },
      ],
    },
  },
  {
    id: "client-bev-armstrong",
    firstName: "Bev",
    lastName: "Armstrong",
    phone: "(250) 555-0111",
    municipality: "Saanich",
    neighborhood: "Cedar Hill",
    addressLine1: "3821 Cedar Hill Rd",
    postalCode: "V8P 3Z8",
    latitude: 48.4638,
    longitude: -123.3331,
    householdSize: 1,
    dietaryTags: ["soft_food"],
    allergenFlags: [],
    accessNotes: "Knock softly after noon medications.",
    request: {
      id: "request-bev-armstrong",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 83,
      priorityLabel: "high",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "assigned",
      routeId: "route-victoria-core",
      assignedStopSequence: 4,
      eta: stamp("2026-04-23T12:58:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Cooler-ready van is already committed to the peninsula run.",
      approvedAt: stamp("2026-04-23T09:34:00-07:00"),
      originalMessageExcerpt:
        "Soft chilled meals are best after my clinic visit. Please knock softly.",
      mealPlan: [
        { mealId: "meal-yogurt-breakfast", quantity: 1 },
        { mealId: "meal-soft-pasta-bake", quantity: 1 },
      ],
    },
  },
  {
    id: "client-keisha-noor",
    firstName: "Keisha",
    lastName: "Noor",
    phone: "(250) 555-0112",
    municipality: "Saanich",
    neighborhood: "Gordon Head",
    addressLine1: "1700 Shelbourne St",
    postalCode: "V8N 3A4",
    latitude: 48.4684,
    longitude: -123.3176,
    householdSize: 1,
    dietaryTags: ["high_protein"],
    allergenFlags: [],
    accessNotes: "Wheelchair transfer takes a minute at the door.",
    assistanceAtDoor: true,
    requiresTwoPerson: true,
    usesWheelchair: true,
    request: {
      id: "request-keisha-noor",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 92,
      priorityLabel: "critical",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-oak-bay-support",
      assignedStopSequence: 3,
      eta: stamp("2026-04-23T13:48:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Wheelchair-lift vehicle is reserved until the afternoon handoff.",
      approvedAt: stamp("2026-04-23T09:39:00-07:00"),
      originalMessageExcerpt:
        "I need the lift-equipped van and someone who can wait while I transfer to the chair at the door.",
      mealPlan: [
        { mealId: "meal-roast-chicken", quantity: 1 },
        { mealId: "meal-fruit-box", quantity: 1 },
      ],
    },
  },
  {
    id: "client-samira-poon",
    firstName: "Samira",
    lastName: "Poon",
    phone: "(250) 555-0113",
    municipality: "Langford",
    neighborhood: "Goldstream",
    addressLine1: "2861 Goldstream Ave",
    postalCode: "V9B 2X2",
    latitude: 48.4473,
    longitude: -123.5007,
    householdSize: 4,
    dietaryTags: ["vegetarian"],
    allergenFlags: ["peanut"],
    accessNotes: "Text first if parking fills up on Goldstream.",
    request: {
      id: "request-samira-poon",
      requestKind: "grocery_hamper",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 86,
      priorityLabel: "high",
      requestedMealCount: 5,
      approvedMealCount: 5,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 2,
      eta: stamp("2026-04-23T14:28:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Produce hamper stock would fall below tomorrow's minimum reserve.",
      approvedAt: stamp("2026-04-23T09:48:00-07:00"),
      originalMessageExcerpt:
        "Vegetarian and peanut-safe hamper, please. Goldstream parking gets tight after lunch.",
      mealPlan: [
        { mealId: "meal-produce-hamper", quantity: 1 },
        { mealId: "meal-lentil-soup", quantity: 4 },
      ],
    },
  },
  {
    id: "client-leonard-voss",
    firstName: "Leonard",
    lastName: "Voss",
    phone: "(250) 555-0114",
    municipality: "Sooke",
    neighborhood: "Town Centre",
    addressLine1: "6726 Sooke Rd",
    postalCode: "V9Z 0A7",
    latitude: 48.3734,
    longitude: -123.7317,
    householdSize: 2,
    dietaryTags: ["low_sodium"],
    allergenFlags: [],
    accessNotes: "Delivery before the school run would help.",
    request: {
      id: "request-leonard-voss",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 72,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 3,
      eta: stamp("2026-04-23T15:04:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "West Shore driver budget would exceed the 75% time cap with this stop.",
      approvedAt: stamp("2026-04-23T09:51:00-07:00"),
      originalMessageExcerpt:
        "Two lower-sodium meals would help. Morning is easier than late afternoon.",
      mealPlan: [
        { mealId: "meal-turkey-dinner", quantity: 1 },
        { mealId: "meal-vegetable-soup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-elena-cortez",
    firstName: "Elena",
    lastName: "Cortez",
    phone: "(250) 555-0115",
    municipality: "Metchosin",
    neighborhood: "Kangaroo",
    addressLine1: "4520 Metchosin Rd",
    postalCode: "V9C 3Z4",
    latitude: 48.3951,
    longitude: -123.5381,
    householdSize: 1,
    dietaryTags: ["gluten_free"],
    allergenFlags: [],
    accessNotes:
      "The gate swings inward; please don't leave coolers on the gravel.",
    request: {
      id: "request-elena-cortez",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 65,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 5,
      eta: stamp("2026-04-23T15:48:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Tomorrow's Metchosin window is waiting on a volunteer with enough daylight.",
      approvedAt: stamp("2026-04-23T09:58:00-07:00"),
      originalMessageExcerpt:
        "Gluten-free is still needed. Please don't leave the cooler bag on the gravel slope.",
      mealPlan: [
        { mealId: "meal-salmon-rice", quantity: 1 },
        { mealId: "meal-fruit-box", quantity: 1 },
      ],
    },
  },
  {
    id: "client-patrick-rowan",
    firstName: "Patrick",
    lastName: "Rowan",
    phone: "(250) 555-0116",
    municipality: "Langford",
    neighborhood: "Bear Mountain",
    addressLine1: "2101 Country Club Way",
    postalCode: "V9B 6R3",
    latitude: 48.4752,
    longitude: -123.5298,
    householdSize: 2,
    dietaryTags: ["diabetic_friendly"],
    allergenFlags: [],
    accessNotes:
      "Lobby stairs are steep; elevator keypad is on the right wall.",
    assistanceAtDoor: true,
    requiresTwoPerson: true,
    request: {
      id: "request-patrick-rowan",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 87,
      priorityLabel: "high",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 4,
      eta: stamp("2026-04-23T15:26:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Two-person assistance flag needs a paired volunteer slot before dispatch.",
      approvedAt: stamp("2026-04-23T10:03:00-07:00"),
      originalMessageExcerpt:
        "A second person is needed at the lobby stairs. Diabetic-friendly please.",
      mealPlan: [
        { mealId: "meal-roast-chicken", quantity: 1 },
        { mealId: "meal-ginger-pear-cup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-amina-yusuf",
    firstName: "Amina",
    lastName: "Yusuf",
    phone: "(250) 555-0117",
    municipality: "Victoria",
    neighborhood: "Hillside-Quadra",
    addressLine1: "1720 Quadra St",
    postalCode: "V8T 4C5",
    latitude: 48.4329,
    longitude: -123.3604,
    householdSize: 3,
    dietaryTags: ["halal"],
    allergenFlags: [],
    accessNotes:
      "Text before arrival because the buzzer directory is out of date.",
    request: {
      id: "request-amina-yusuf",
      requestKind: "grocery_hamper",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 81,
      priorityLabel: "high",
      requestedMealCount: 4,
      approvedMealCount: 4,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-victoria-core",
      assignedStopSequence: 5,
      eta: stamp("2026-04-23T13:09:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Access note is low confidence and needs a quick coordinator call.",
      approvedAt: stamp("2026-04-23T10:09:00-07:00"),
      originalMessageExcerpt:
        "Halal-friendly groceries would help. Please text because the lobby list is wrong again.",
      mealPlan: [
        { mealId: "meal-produce-hamper", quantity: 1 },
        { mealId: "meal-lentil-soup", quantity: 3 },
      ],
    },
  },
  {
    id: "client-bill-holtz",
    firstName: "Bill",
    lastName: "Holtz",
    phone: "(250) 555-0118",
    municipality: "Victoria",
    neighborhood: "Oaklands",
    addressLine1: "1245 Haultain St",
    postalCode: "V8T 2L9",
    latitude: 48.4393,
    longitude: -123.3452,
    householdSize: 1,
    dietaryTags: ["soft_food"],
    allergenFlags: [],
    accessNotes: "Try the courtyard gate first if the front ramp is busy.",
    request: {
      id: "request-bill-holtz",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 63,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-victoria-core",
      assignedStopSequence: 6,
      eta: stamp("2026-04-23T13:21:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Tomorrow route bundle is full and this stop is next up if a slot opens.",
      approvedAt: stamp("2026-04-23T10:16:00-07:00"),
      originalMessageExcerpt:
        "Soft meals are still best. The courtyard gate is easier than the front ramp.",
      mealPlan: [
        { mealId: "meal-soft-pasta-bake", quantity: 1 },
        { mealId: "meal-vegetable-soup", quantity: 1 },
      ],
    },
  },
  {
    id: "client-maryam-lai",
    firstName: "Maryam",
    lastName: "Lai",
    phone: "(250) 555-0119",
    municipality: "Oak Bay",
    neighborhood: "South Oak Bay",
    addressLine1: "1495 Beach Dr",
    postalCode: "V8S 2N4",
    latitude: 48.4091,
    longitude: -123.3215,
    householdSize: 2,
    dietaryTags: ["lactose_free"],
    allergenFlags: [],
    accessNotes:
      "Morning is best before the support worker heads to clinic rounds.",
    request: {
      id: "request-maryam-lai",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 60,
      priorityLabel: "low",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "assigned",
      routeId: "route-oak-bay-support",
      assignedStopSequence: 4,
      eta: stamp("2026-04-23T14:05:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Later-date request can be pulled forward once chilled stock is ready.",
      approvedAt: stamp("2026-04-23T10:22:00-07:00"),
      originalMessageExcerpt:
        "Lactose-free and ideally before noon. The support worker leaves right after lunch.",
      mealPlan: [
        { mealId: "meal-yogurt-breakfast", quantity: 1 },
        { mealId: "meal-roast-chicken", quantity: 1 },
      ],
    },
  },
  {
    id: "client-theo-palmer",
    firstName: "Theo",
    lastName: "Palmer",
    phone: "(250) 555-0120",
    municipality: "Saanich",
    neighborhood: "Uptown",
    addressLine1: "3655 Ravine Way",
    postalCode: "V8X 4Z1",
    latitude: 48.4588,
    longitude: -123.3774,
    householdSize: 1,
    dietaryTags: ["renal_friendly"],
    allergenFlags: [],
    accessNotes:
      "Call from the loading zone because the front desk rotates staff.",
    request: {
      id: "request-theo-palmer",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 78,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-victoria-core",
      assignedStopSequence: 7,
      eta: stamp("2026-04-23T13:35:00-07:00"),
      stopStatus: "planned",
      routingHoldReason:
        "Front-desk handoff instructions still need a confirmation call.",
      approvedAt: stamp("2026-04-23T10:27:00-07:00"),
      originalMessageExcerpt:
        "Renal-friendly trays please. Call from the loading zone because the front desk rotates staff.",
      mealPlan: [
        { mealId: "meal-turkey-dinner", quantity: 1 },
        { mealId: "meal-fruit-box", quantity: 1 },
      ],
    },
  },
  {
    id: "client-nadia-singh",
    firstName: "Nadia",
    lastName: "Singh",
    phone: "(250) 555-0121",
    municipality: "Victoria",
    neighborhood: "Fernwood",
    addressLine1: "1534 Pembroke St",
    postalCode: "V8R 1R5",
    latitude: 48.4315,
    longitude: -123.3459,
    householdSize: 4,
    dietaryTags: ["peanut_safe"],
    allergenFlags: ["peanut"],
    accessNotes: "Text first because the intercom is unreliable again.",
    request: {
      id: "request-nadia-singh",
      requestKind: "grocery_hamper",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 82,
      priorityLabel: "high",
      requestedMealCount: 4,
      approvedMealCount: 4,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-victoria-core",
      assignedStopSequence: 8,
      approvedAt: stamp("2026-04-23T10:33:00-07:00"),
      eta: stamp("2026-04-23T13:49:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Four shelf-stable meals or a grocery hamper would help today. Please keep it peanut-safe and text before arrival.",
      mealPlan: [
        { mealId: "meal-produce-hamper", quantity: 1 },
        { mealId: "meal-lentil-soup", quantity: 3 },
      ],
    },
  },
  {
    id: "client-greta-chan",
    firstName: "Greta",
    lastName: "Chan",
    phone: "(250) 555-0122",
    municipality: "Sidney",
    neighborhood: "Beacon",
    addressLine1: "9831 Fourth St",
    postalCode: "V8L 2Z1",
    latitude: 48.6496,
    longitude: -123.3991,
    householdSize: 1,
    dietaryTags: ["low_sodium"],
    allergenFlags: [],
    accessNotes: "Leave with the front desk if the physio visit runs late.",
    request: {
      id: "request-greta-chan",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 74,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: true,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 6,
      approvedAt: stamp("2026-04-23T10:37:00-07:00"),
      eta: stamp("2026-04-23T16:04:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Two low-sodium chilled meals would help after physio. The front desk can receive them if needed.",
      mealPlan: [
        { mealId: "meal-turkey-dinner", quantity: 1 },
        { mealId: "meal-yogurt-breakfast", quantity: 1 },
      ],
    },
  },
  {
    id: "client-omar-reid",
    firstName: "Omar",
    lastName: "Reid",
    phone: "(250) 555-0123",
    municipality: "Sooke",
    neighborhood: "Broomhill",
    addressLine1: "2068 Church Rd",
    postalCode: "V9Z 0W7",
    latitude: 48.3794,
    longitude: -123.7194,
    householdSize: 3,
    dietaryTags: ["halal"],
    allergenFlags: [],
    accessNotes: "Use the side gate by the cedar fence.",
    assistanceAtDoor: true,
    request: {
      id: "request-omar-reid",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 77,
      priorityLabel: "normal",
      requestedMealCount: 3,
      approvedMealCount: 3,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 7,
      approvedAt: stamp("2026-04-23T10:41:00-07:00"),
      eta: stamp("2026-04-23T16:22:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Three halal meals are needed today. The side gate by the cedar fence is easiest.",
      mealPlan: [
        { mealId: "meal-ginger-chicken-rice", quantity: 2 },
        { mealId: "meal-fruit-box", quantity: 1 },
      ],
    },
  },
  {
    id: "client-tess-monroe",
    firstName: "Tess",
    lastName: "Monroe",
    phone: "(250) 555-0124",
    municipality: "Langford",
    neighborhood: "Florence Lake",
    addressLine1: "2576 Millstream Rd",
    postalCode: "V9B 3R3",
    latitude: 48.4742,
    longitude: -123.4946,
    householdSize: 2,
    dietaryTags: ["soft_food"],
    allergenFlags: [],
    accessNotes: "Knock twice; the doorbell is disconnected.",
    request: {
      id: "request-tess-monroe",
      requestKind: "meal_delivery",
      dueBucket: "today",
      scheduledDate: TODAY,
      urgencyScore: 70,
      priorityLabel: "normal",
      requestedMealCount: 2,
      approvedMealCount: 2,
      coldChainRequired: false,
      status: "assigned",
      routeId: "route-peninsula-run",
      assignedStopSequence: 8,
      approvedAt: stamp("2026-04-23T10:45:00-07:00"),
      eta: stamp("2026-04-23T16:39:00-07:00"),
      stopStatus: "planned",
      originalMessageExcerpt:
        "Two soft meals would help today. Please knock twice because the doorbell is disconnected.",
      mealPlan: [
        { mealId: "meal-soft-pasta-bake", quantity: 1 },
        { mealId: "meal-vegetable-soup", quantity: 1 },
      ],
    },
  },
];

export type SeedDataset = {
  depots: NewDepot[];
  intakeMessages: NewIntakeMessage[];
  intakeDrafts: NewIntakeDraft[];
  clients: NewClient[];
  volunteers: NewVolunteer[];
  volunteerAvailability: NewVolunteerAvailability[];
  vehicles: NewVehicle[];
  deliveryRequests: NewDeliveryRequest[];
  deliverableMeals: NewDeliverableMeal[];
  ingredientItems: NewIngredientItem[];
  routes: NewRoute[];
  routeStops: NewRouteStop[];
  routeStopMealItems: NewRouteStopMealItem[];
  driverSessions: NewDriverSession[];
};

export function buildSeedDataset(): SeedDataset {
  const depotsSeed: NewDepot[] = [
    {
      id: "depot-victoria-central",
      name: "Victoria Central Depot",
      municipality: "Victoria",
      addressLine: "620 Yates St, Victoria, BC",
      latitude: 48.4291,
      longitude: -123.3748,
      hoursStart: "06:00",
      hoursEnd: "18:00",
      notes:
        "Main hot-meal staging kitchen for the downtown and Oak Bay loops.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "depot-saanich-satellite",
      name: "Saanich Satellite Depot",
      municipality: "Saanich",
      addressLine: "3980 Quadra St, Saanich, BC",
      latitude: 48.4778,
      longitude: -123.4028,
      hoursStart: "07:00",
      hoursEnd: "17:00",
      notes: "Overflow hamper staging and peninsula cooler handoff point.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
  ];

  const intakeMessagesSeed: NewIntakeMessage[] = [
    {
      id: "intake-request-fernwood",
      channel: "gmail",
      intakeKind: "request",
      senderName: "Harbourline family desk",
      senderEmail: "intake@harbourline-help.example",
      senderPhone: "(250) 555-0191",
      subject: "Need hamper before supper",
      rawBody:
        "Hi Mealflo team,\n\nHarbourline is helping Nadia Singh's family at 1534 Pembroke St in Fernwood. There are four people at home and they could use four shelf-stable meals or a grocery hamper today if one is possible.\n\nPlease keep it peanut-safe. Text Nadia at (250) 555-0191 before arrival because the intercom is unreliable again.\n\nThanks,\nHarbourline family desk",
      rawAddress: "1534 Pembroke St, Victoria, BC",
      sourcePayload: {
        mailbox: "demo-intake",
        messageId: "gmail-demo-001",
      },
      status: "draft_ready",
      receivedAt: stamp("2026-04-23T10:42:00-07:00"),
      createdAt: stamp("2026-04-23T10:42:00-07:00"),
      updatedAt: stamp("2026-04-23T10:49:00-07:00"),
    },
    {
      id: "intake-volunteer-jules",
      channel: "public_form",
      intakeKind: "volunteer",
      senderName: "Jules Carter",
      senderEmail: "jules.carter@example.com",
      senderPhone: "(250) 555-0192",
      subject: "Volunteer after work",
      rawBody:
        "Availability + location: Today after 4:30pm until 6:00pm, 90 minutes, starting in Oaklands, Victoria.\nVehicle access: Car, my own hatchback.\nCan bring a cooler: No.\nStairs: Comfortable.\nAnything else to share: I can do a short after-work route, but I am not comfortable with refrigerated totes yet.",
      rawAddress: "Oaklands, Victoria, BC",
      sourcePayload: {
        form: "public-volunteer",
      },
      status: "draft_ready",
      receivedAt: stamp("2026-04-23T09:56:00-07:00"),
      createdAt: stamp("2026-04-23T09:56:00-07:00"),
      updatedAt: stamp("2026-04-23T10:05:00-07:00"),
    },
    {
      id: "intake-request-esquimalt",
      channel: "public_form",
      intakeKind: "request",
      senderName: "Mara Ellis",
      senderPhone: "(250) 555-0193",
      subject: "Request for chilled meals",
      rawBody:
        "Two chilled meals would really help after a clinic visit. Please knock softly and give me a minute to get to the door.",
      rawAddress: "3821 Cedar Hill Rd, Saanich, BC",
      sourcePayload: {
        form: "public-request",
      },
      status: "draft_ready",
      receivedAt: stamp("2026-04-23T09:21:00-07:00"),
      createdAt: stamp("2026-04-23T09:21:00-07:00"),
      updatedAt: stamp("2026-04-23T09:29:00-07:00"),
    },
    {
      id: "intake-request-hillside",
      channel: "gmail",
      intakeKind: "request",
      senderName: "Amina Yusuf",
      senderEmail: "amina.yusuf@example.com",
      senderPhone: "(250) 555-0117",
      subject: "Buzzer directory is wrong again",
      rawBody:
        "Hello Mealflo,\n\nThis is Amina Yusuf at 1720 Quadra St, Victoria. We have three people at home and four halal-friendly grocery meals would help today.\n\nPlease text me at (250) 555-0117 before arrival because the buzzer directory still sends people to the wrong unit.\n\nThank you,\nAmina",
      rawAddress: "1720 Quadra St, Victoria, BC",
      sourcePayload: {
        mailbox: "demo-intake",
        messageId: "gmail-demo-004",
      },
      status: "draft_ready",
      receivedAt: stamp("2026-04-23T09:34:00-07:00"),
      createdAt: stamp("2026-04-23T09:34:00-07:00"),
      updatedAt: stamp("2026-04-23T09:44:00-07:00"),
    },
    {
      id: "intake-volunteer-approved",
      channel: "public_form",
      intakeKind: "volunteer",
      senderName: "Leah Nordin",
      senderEmail: "leah.nordin@example.com",
      senderPhone: "(250) 555-0194",
      subject: "Available in James Bay today",
      rawBody:
        "I can take a 60 minute run from James Bay this afternoon and I'm okay with cooler totes.",
      rawAddress: "James Bay, Victoria, BC",
      sourcePayload: {
        form: "public-volunteer",
      },
      status: "approved",
      receivedAt: stamp("2026-04-23T08:18:00-07:00"),
      createdAt: stamp("2026-04-23T08:18:00-07:00"),
      updatedAt: stamp("2026-04-23T08:40:00-07:00"),
    },
    {
      id: "intake-request-approved",
      channel: "gmail",
      intakeKind: "request",
      senderName: "North Park neighbour line",
      senderEmail: "dispatch@northpark-neighbours.example",
      senderPhone: "(250) 555-0195",
      subject: "Soft food request",
      rawBody:
        "Hi,\n\nNoel Okafor is at 901 Caledonia Ave in Victoria. Two people at home could use three soft-food meals today. Please keep the meals peanut-free.\n\nText Noel at (250) 555-0195 first because the call box is hit and miss.\n\nNorth Park neighbour line",
      rawAddress: "901 Caledonia Ave, Victoria, BC",
      sourcePayload: {
        mailbox: "demo-intake",
        messageId: "gmail-demo-006",
      },
      status: "approved",
      receivedAt: stamp("2026-04-23T08:02:00-07:00"),
      createdAt: stamp("2026-04-23T08:02:00-07:00"),
      updatedAt: stamp("2026-04-23T08:32:00-07:00"),
    },
  ];

  const intakeDraftsSeed: NewIntakeDraft[] = [
    {
      id: "draft-request-fernwood",
      intakeMessageId: "intake-request-fernwood",
      draftType: "request",
      structuredPayload: {
        firstName: "Nadia",
        lastName: "Singh",
        municipality: "Victoria",
        neighborhood: "Fernwood",
        addressLine1: "1534 Pembroke St",
        householdSize: 4,
        dietaryTags: ["peanut_safe"],
        allergenFlags: ["peanut"],
        dueBucket: "today",
        requestedMealCount: 4,
        coldChainRequired: false,
        message:
          "Harbourline is helping Nadia Singh's family at 1534 Pembroke St in Fernwood. There are four people at home and they could use four shelf-stable meals or a grocery hamper today if one is possible. Please keep it peanut-safe. Text Nadia before arrival because the intercom is unreliable again.",
        accessNotes:
          "Text before arrival because the intercom is unreliable again.",
      },
      confidenceScore: 91,
      lowConfidenceFields: ["addressLine1"],
      summary: "Family hamper request in Fernwood with peanut-safe note.",
      parserVersion: "foundation-v1",
      status: "pending",
      createdAt: stamp("2026-04-23T10:45:00-07:00"),
      updatedAt: stamp("2026-04-23T10:49:00-07:00"),
    },
    {
      id: "draft-volunteer-jules",
      intakeMessageId: "intake-volunteer-jules",
      draftType: "volunteer",
      structuredPayload: {
        firstName: "Jules",
        lastName: "Carter",
        homeArea: "Oaklands",
        homeMunicipality: "Victoria",
        hasVehicleAccess: true,
        canClimbStairs: true,
        canHandleColdChain: false,
        minutesAvailable: 90,
        windowStart: "16:30",
        windowEnd: "18:00",
        message:
          "I can do a short after-work route, but I am not comfortable with refrigerated totes yet.",
      },
      confidenceScore: 88,
      lowConfidenceFields: ["minutesAvailable"],
      summary: "After-work volunteer in Oaklands with hatchback access.",
      parserVersion: "foundation-v1",
      status: "pending",
      createdAt: stamp("2026-04-23T09:58:00-07:00"),
      updatedAt: stamp("2026-04-23T10:05:00-07:00"),
    },
    {
      id: "draft-request-chilled",
      intakeMessageId: "intake-request-esquimalt",
      draftType: "request",
      structuredPayload: {
        firstName: "Mara",
        lastName: "Ellis",
        municipality: "Saanich",
        neighborhood: "Cedar Hill",
        addressLine1: "3821 Cedar Hill Rd",
        householdSize: 1,
        dietaryTags: ["soft_food"],
        allergenFlags: [],
        dueBucket: "today",
        requestedMealCount: 2,
        coldChainRequired: true,
        message:
          "Two chilled meals would really help after a clinic visit. Please knock softly and give me a minute to get to the door.",
        accessNotes: "Knock softly after noon medications.",
      },
      confidenceScore: 87,
      lowConfidenceFields: ["accessNotes"],
      summary: "Cedar Hill chilled-meal request with soft-food note.",
      parserVersion: "foundation-v1",
      status: "pending",
      createdAt: stamp("2026-04-23T09:23:00-07:00"),
      updatedAt: stamp("2026-04-23T09:29:00-07:00"),
    },
    {
      id: "draft-request-hillside",
      intakeMessageId: "intake-request-hillside",
      draftType: "request",
      structuredPayload: {
        firstName: "Amina",
        lastName: "Yusuf",
        municipality: "Victoria",
        neighborhood: "Hillside-Quadra",
        addressLine1: "1720 Quadra St",
        householdSize: 3,
        dietaryTags: ["halal"],
        allergenFlags: [],
        dueBucket: "today",
        requestedMealCount: 4,
        coldChainRequired: false,
        message:
          "Amina Yusuf at 1720 Quadra St has three people at home and four halal-friendly grocery meals would help today. Please text before arrival because the buzzer directory still sends people to the wrong unit.",
        accessNotes:
          "Text before arrival because the buzzer directory is out of date.",
      },
      confidenceScore: 83,
      lowConfidenceFields: ["accessNotes"],
      summary: "Halal-friendly grocery request with buzzer issue.",
      parserVersion: "foundation-v1",
      status: "pending",
      createdAt: stamp("2026-04-23T09:36:00-07:00"),
      updatedAt: stamp("2026-04-23T09:44:00-07:00"),
    },
    {
      id: "draft-volunteer-approved",
      intakeMessageId: "intake-volunteer-approved",
      draftType: "volunteer",
      structuredPayload: {
        firstName: "Leah",
        lastName: "Nordin",
        homeArea: "James Bay",
        homeMunicipality: "Victoria",
        hasVehicleAccess: true,
        canClimbStairs: true,
        canHandleColdChain: true,
        minutesAvailable: 60,
        windowStart: "13:00",
        windowEnd: "15:00",
        message:
          "I can take a 60 minute run from James Bay this afternoon and I'm okay with cooler totes.",
      },
      confidenceScore: 95,
      lowConfidenceFields: [],
      summary: "James Bay volunteer approved for cooler afternoon runs.",
      parserVersion: "foundation-v1",
      approvedRecordType: "volunteer",
      approvedRecordId: "volunteer-leah-nordin",
      reviewedAt: stamp("2026-04-23T08:40:00-07:00"),
      reviewedBy: "Sarah, coordinator",
      status: "approved",
      createdAt: stamp("2026-04-23T08:19:00-07:00"),
      updatedAt: stamp("2026-04-23T08:40:00-07:00"),
    },
    {
      id: "draft-request-approved",
      intakeMessageId: "intake-request-approved",
      draftType: "request",
      structuredPayload: {
        firstName: "Noel",
        lastName: "Okafor",
        municipality: "Victoria",
        neighborhood: "North Park",
        addressLine1: "901 Caledonia Ave",
        householdSize: 2,
        dietaryTags: ["soft_food"],
        allergenFlags: ["peanut"],
        dueBucket: "today",
        requestedMealCount: 3,
        coldChainRequired: false,
        message:
          "Soft meals are still the easiest. Text first because the call box is hit and miss.",
        accessNotes: "Text first because the call box is hit and miss.",
      },
      confidenceScore: 93,
      lowConfidenceFields: [],
      summary: "North Park soft-food request approved into today's route.",
      parserVersion: "foundation-v1",
      approvedRecordType: "delivery_request",
      approvedRecordId: "request-noel-okafor",
      reviewedAt: stamp("2026-04-23T08:32:00-07:00"),
      reviewedBy: "Sarah, coordinator",
      status: "approved",
      createdAt: stamp("2026-04-23T08:05:00-07:00"),
      updatedAt: stamp("2026-04-23T08:32:00-07:00"),
    },
  ];

  const volunteersSeed: NewVolunteer[] = [
    {
      id: "volunteer-rosa-martinez",
      firstName: "Rosa",
      lastName: "Martinez",
      phone: "(250) 555-0201",
      email: "rosa.martinez@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Fernwood",
      homeMunicipality: "Victoria",
      hasVehicleAccess: true,
      preferredVehicleId: "vehicle-bluebird-cooler",
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "Spanish"],
      notes: "Strong on short downtown routes.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-calvin-leung",
      firstName: "Calvin",
      lastName: "Leung",
      phone: "(250) 555-0202",
      email: "calvin.leung@mealflo-demo.example",
      role: "staff",
      homeArea: "Vic West",
      homeMunicipality: "Victoria",
      hasVehicleAccess: true,
      preferredVehicleId: "vehicle-harbour-van",
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "Cantonese"],
      notes: "Can take longer lunch loops when needed.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-amira-patel",
      firstName: "Amira",
      lastName: "Patel",
      phone: "(250) 555-0203",
      email: "amira.patel@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Oak Bay",
      homeMunicipality: "Oak Bay",
      hasVehicleAccess: true,
      preferredVehicleId: "vehicle-oak-bay-lift",
      canHandleColdChain: false,
      canHandleWheelchair: true,
      canClimbStairs: true,
      languages: ["English", "Gujarati"],
      notes: "Best on Oak Bay and Jubilee routes.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-owen-mercier",
      firstName: "Owen",
      lastName: "Mercier",
      phone: "(250) 555-0204",
      email: "owen.mercier@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Sidney",
      homeMunicipality: "Sidney",
      hasVehicleAccess: true,
      preferredVehicleId: "vehicle-peninsula-wagon",
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "French"],
      notes: "Longer peninsula runs, calm with time windows.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-talia-brooks",
      firstName: "Talia",
      lastName: "Brooks",
      phone: "(250) 555-0205",
      email: "talia.brooks@mealflo-demo.example",
      role: "staff",
      homeArea: "Colwood",
      homeMunicipality: "Colwood",
      hasVehicleAccess: true,
      preferredVehicleId: "vehicle-westshore-link",
      canHandleColdChain: false,
      canHandleWheelchair: true,
      canClimbStairs: true,
      languages: ["English"],
      notes: "West Shore fallback driver and route checker.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-leah-nordin",
      sourceIntakeDraftId: "draft-volunteer-approved",
      firstName: "Leah",
      lastName: "Nordin",
      phone: "(250) 555-0194",
      email: "leah.nordin@example.com",
      role: "volunteer",
      homeArea: "James Bay",
      homeMunicipality: "Victoria",
      hasVehicleAccess: true,
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English"],
      notes: "Recently approved intake, great for last-minute fill-ins.",
      active: true,
      createdAt: stamp("2026-04-23T08:40:00-07:00"),
      updatedAt: stamp("2026-04-23T08:40:00-07:00"),
    },
    {
      id: "volunteer-micah-shah",
      firstName: "Micah",
      lastName: "Shah",
      phone: "(250) 555-0206",
      email: "micah.shah@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Uptown",
      homeMunicipality: "Saanich",
      hasVehicleAccess: false,
      canHandleColdChain: false,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "Hindi"],
      notes: "Transit-based helper for paired downtown routes.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-sara-adjei",
      firstName: "Sara",
      lastName: "Adjei",
      phone: "(250) 555-0207",
      email: "sara.adjei@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Langford",
      homeMunicipality: "Langford",
      hasVehicleAccess: true,
      canHandleColdChain: false,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "Twi"],
      notes: "Available for short late-day West Shore handoffs.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-elliot-price",
      firstName: "Elliot",
      lastName: "Price",
      phone: "(250) 555-0208",
      email: "elliot.price@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Esquimalt",
      homeMunicipality: "Esquimalt",
      hasVehicleAccess: true,
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English"],
      notes: "Steady cooler backup on weekday mornings.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "volunteer-reina-collins",
      firstName: "Reina",
      lastName: "Collins",
      phone: "(250) 555-0209",
      email: "reina.collins@mealflo-demo.example",
      role: "volunteer",
      homeArea: "Sidney",
      homeMunicipality: "Sidney",
      hasVehicleAccess: true,
      canHandleColdChain: true,
      canHandleWheelchair: false,
      canClimbStairs: true,
      languages: ["English", "Tagalog"],
      notes: "Useful for peninsula overflow and bilingual check-ins.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
  ];

  const volunteerAvailabilitySeed: NewVolunteerAvailability[] =
    volunteersSeed.map((volunteer, index) => {
      const minutesOptions = [90, 75, 60, 90, 75, 60, 45, 45, 60, 75];
      const startHour = index < 5 ? "10:00" : "13:00";
      const endHour = index < 5 ? "13:00" : "15:00";

      return {
        id: `availability-${volunteer.id}`,
        volunteerId: volunteer.id,
        source:
          volunteer.id === "volunteer-leah-nordin" ? "public_form" : "seeded",
        rawText:
          volunteer.id === "volunteer-leah-nordin"
            ? "Available for about an hour this afternoon from James Bay."
            : "Regular demo availability",
        recurringRule:
          volunteer.id === "volunteer-leah-nordin"
            ? undefined
            : "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR",
        date: day(index < 5 ? TODAY : TOMORROW),
        windowStart: startHour,
        windowEnd: endHour,
        minutesAvailable: minutesOptions[index] ?? 60,
        parsedConfidence: volunteer.id === "volunteer-leah-nordin" ? 95 : 100,
        createdAt: sharedCreatedAt,
        updatedAt: SEED_NOW,
      };
    });

  const vehiclesSeed: NewVehicle[] = [
    {
      id: "vehicle-bluebird-cooler",
      name: "Bluebird cooler car",
      type: "refrigerated_van",
      refrigerated: true,
      wheelchairLift: false,
      capacityMeals: 28,
      homeDepotId: "depot-victoria-central",
      notes: "Compact cooler load for downtown and James Bay.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "vehicle-harbour-van",
      name: "Harbour cargo van",
      type: "cargo_van",
      refrigerated: true,
      wheelchairLift: false,
      capacityMeals: 42,
      homeDepotId: "depot-victoria-central",
      notes: "Main Esquimalt and Vic West runner.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "vehicle-oak-bay-lift",
      name: "Oak Bay lift van",
      type: "cargo_van",
      refrigerated: false,
      wheelchairLift: true,
      capacityMeals: 24,
      homeDepotId: "depot-victoria-central",
      notes: "Only lift-equipped vehicle in the demo fleet.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "vehicle-peninsula-wagon",
      name: "Peninsula hybrid wagon",
      type: "hatchback",
      refrigerated: true,
      wheelchairLift: false,
      capacityMeals: 20,
      homeDepotId: "depot-saanich-satellite",
      notes: "Longer distance, smaller chilled loadout.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "vehicle-westshore-link",
      name: "West Shore link van",
      type: "cargo_van",
      refrigerated: false,
      wheelchairLift: false,
      capacityMeals: 34,
      homeDepotId: "depot-saanich-satellite",
      notes: "Best for Langford, Colwood, and Metchosin runs.",
      active: true,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
  ];

  const deliverableMealsSeed: NewDeliverableMeal[] = [
    {
      id: "meal-roast-chicken",
      name: "Roast chicken and vegetables",
      category: "hot_meal",
      quantityAvailable: 10,
      allergenFlags: [],
      dietaryTags: ["high_protein"],
      refrigerated: true,
      unitLabel: "tray",
      sourceNote: "Prepared at Victoria Central this morning.",
      lowStockThreshold: 4,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-vegetable-soup",
      name: "Garden vegetable soup",
      category: "soup",
      quantityAvailable: 12,
      allergenFlags: [],
      dietaryTags: ["vegetarian", "low_sodium"],
      refrigerated: false,
      unitLabel: "container",
      sourceNote: "Shelf-stable for same-day runs.",
      lowStockThreshold: 5,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-soft-pasta-bake",
      name: "Soft pasta bake",
      category: "hot_meal",
      quantityAvailable: 6,
      allergenFlags: ["wheat", "dairy"],
      dietaryTags: ["soft_food"],
      refrigerated: true,
      unitLabel: "tray",
      sourceNote: "Reserved for texture-modified requests.",
      lowStockThreshold: 3,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-ginger-pear-cup",
      name: "Ginger pear cup",
      category: "snack",
      quantityAvailable: 9,
      allergenFlags: [],
      dietaryTags: ["soft_food"],
      refrigerated: false,
      unitLabel: "cup",
      sourceNote: "Easy add-on for soft-food routes.",
      lowStockThreshold: 4,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-salmon-rice",
      name: "Salmon and rice bowl",
      category: "hot_meal",
      quantityAvailable: 5,
      allergenFlags: ["fish"],
      dietaryTags: ["gluten_free"],
      refrigerated: true,
      unitLabel: "bowl",
      sourceNote: "Needs refrigeration.",
      lowStockThreshold: 3,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-vegetable-curry",
      name: "Vegetable curry",
      category: "hot_meal",
      quantityAvailable: 8,
      allergenFlags: [],
      dietaryTags: ["vegetarian", "dairy_free"],
      refrigerated: false,
      unitLabel: "tray",
      sourceNote: "Pairs well with later-day Oak Bay routes.",
      lowStockThreshold: 3,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-lentil-soup",
      name: "Red lentil soup",
      category: "soup",
      quantityAvailable: 14,
      allergenFlags: [],
      dietaryTags: ["vegetarian", "dairy_free"],
      refrigerated: false,
      unitLabel: "container",
      sourceNote: "Often packed into hamper runs.",
      lowStockThreshold: 6,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-produce-hamper",
      name: "Produce hamper",
      category: "hamper",
      quantityAvailable: 7,
      allergenFlags: [],
      dietaryTags: ["fresh"],
      refrigerated: false,
      unitLabel: "hamper",
      sourceNote: "Mixed pantry and fresh produce bundle.",
      lowStockThreshold: 4,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-yogurt-breakfast",
      name: "Yogurt breakfast pack",
      category: "breakfast",
      quantityAvailable: 4,
      allergenFlags: ["dairy"],
      dietaryTags: ["high_protein"],
      refrigerated: true,
      unitLabel: "pack",
      sourceNote: "Needs refrigeration for breakfast add-on.",
      lowStockThreshold: 3,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-turkey-dinner",
      name: "Turkey dinner tray",
      category: "hot_meal",
      quantityAvailable: 6,
      allergenFlags: [],
      dietaryTags: ["low_sodium"],
      refrigerated: true,
      unitLabel: "tray",
      sourceNote: "Popular with lower-sodium regulars.",
      lowStockThreshold: 3,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-ginger-chicken-rice",
      name: "Ginger chicken and rice",
      category: "hot_meal",
      quantityAvailable: 9,
      allergenFlags: [],
      dietaryTags: ["halal"],
      refrigerated: true,
      unitLabel: "tray",
      sourceNote: "Prepared with the cultural meal rotation.",
      lowStockThreshold: 4,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "meal-fruit-box",
      name: "Fresh fruit box",
      category: "hamper",
      quantityAvailable: 10,
      allergenFlags: [],
      dietaryTags: ["fresh", "dairy_free"],
      refrigerated: false,
      unitLabel: "box",
      sourceNote: "Easy add-on for supportive food boxes.",
      lowStockThreshold: 5,
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
  ];

  const ingredientItemsSeed: NewIngredientItem[] = [
    {
      id: "ingredient-yukon-potatoes",
      name: "Yukon potatoes",
      quantity: 18,
      unit: "crates",
      refrigerated: false,
      perishabilityScore: 2,
      perishabilityLabel: "Stable",
      sourceType: "purchase",
      sourceReference: "Thursday produce order",
      notes: "Next roast cycle is covered through the weekend.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-carrots",
      name: "Carrots",
      quantity: 11,
      unit: "crates",
      refrigerated: true,
      perishabilityScore: 4,
      perishabilityLabel: "Use soon",
      sourceType: "farm",
      sourceReference: "North Saanich farm drop",
      notes: "Good candidate for tomorrow's soup base.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-yogurt",
      name: "Yogurt cups",
      quantity: 24,
      unit: "cups",
      refrigerated: true,
      perishabilityScore: 5,
      perishabilityLabel: "Needs refrigeration",
      sourceType: "purchase",
      sourceReference: "Wholesale dairy invoice 2331",
      notes:
        "Only four breakfast packs are packed; the rest are still loose stock.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-lentils",
      name: "Dry red lentils",
      quantity: 30,
      unit: "bags",
      refrigerated: false,
      perishabilityScore: 1,
      perishabilityLabel: "Stable",
      sourceType: "pantry",
      sourceReference: "Dry goods reserve",
      notes: "Enough for next week's hamper soup run.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-apples",
      name: "Apples",
      quantity: 20,
      unit: "bags",
      refrigerated: false,
      perishabilityScore: 3,
      perishabilityLabel: "Use this week",
      sourceType: "donation",
      sourceReference: "Community pantry pickup",
      notes: "Looks good on the dashboard and moves fast in hampers.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-rice",
      name: "Rice",
      quantity: 16,
      unit: "bags",
      refrigerated: false,
      perishabilityScore: 1,
      perishabilityLabel: "Stable",
      sourceType: "purchase",
      sourceReference: "Bulk dry goods order",
      notes: "Base ingredient for several hot meals.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-pears",
      name: "Canned pears",
      quantity: 14,
      unit: "cases",
      refrigerated: false,
      perishabilityScore: 2,
      perishabilityLabel: "Stable",
      sourceType: "hub_transfer",
      sourceReference: "Regional hub transfer",
      notes: "Supports the soft-food add-on cups.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
    {
      id: "ingredient-spinach",
      name: "Spinach",
      quantity: 9,
      unit: "bags",
      refrigerated: true,
      perishabilityScore: 5,
      perishabilityLabel: "Use today",
      sourceType: "donation",
      sourceReference: "Morning grocery rescue",
      notes: "Good visible candidate for perishability triage.",
      createdAt: sharedCreatedAt,
      updatedAt: SEED_NOW,
    },
  ];

  const clientsSeed: NewClient[] = householdSeeds.map((household) => ({
    id: household.id,
    sourceIntakeDraftId:
      household.id === "client-noel-okafor"
        ? "draft-request-approved"
        : undefined,
    firstName: household.firstName,
    lastName: household.lastName,
    preferredName: household.preferredName,
    phone: household.phone,
    municipality: household.municipality,
    neighborhood: household.neighborhood,
    addressLine1: household.addressLine1,
    postalCode: household.postalCode,
    latitude: household.latitude,
    longitude: household.longitude,
    householdSize: household.householdSize,
    dietaryTags: household.dietaryTags,
    allergenFlags: household.allergenFlags,
    accessNotes: household.accessNotes,
    safeToLeave: household.safeToLeave ?? false,
    doNotEnter: household.doNotEnter ?? false,
    assistanceAtDoor: household.assistanceAtDoor ?? false,
    requiresTwoPerson: household.requiresTwoPerson ?? false,
    usesWheelchair: household.usesWheelchair ?? false,
    active: true,
    notes: household.notes,
    lastApprovedRequestAt: household.request.approvedAt,
    createdAt: sharedCreatedAt,
    updatedAt: SEED_NOW,
  }));

  const deliveryRequestsSeed: NewDeliveryRequest[] = householdSeeds.map(
    (household) => ({
      id: household.request.id,
      clientId: household.id,
      sourceIntakeDraftId:
        household.id === "client-noel-okafor"
          ? "draft-request-approved"
          : undefined,
      requestKind: household.request.requestKind,
      dueBucket: household.request.dueBucket,
      scheduledDate: day(household.request.scheduledDate),
      urgencyScore: household.request.urgencyScore,
      priorityLabel: household.request.priorityLabel,
      householdSizeSnapshot: household.householdSize,
      requestedMealCount: household.request.requestedMealCount,
      approvedMealCount: household.request.approvedMealCount,
      coldChainRequired: household.request.coldChainRequired,
      dietaryTagsSnapshot: household.dietaryTags,
      allergenFlagsSnapshot: household.allergenFlags,
      accessNotes: household.accessNotes,
      originalMessageExcerpt: household.request.originalMessageExcerpt,
      notes: household.request.notes,
      routingHoldReason: household.request.routingHoldReason,
      status: household.request.status,
      approvedAt: household.request.approvedAt,
      assignedRouteId: household.request.routeId,
      assignedStopSequence: household.request.assignedStopSequence,
      createdAt: addMinutes(household.request.approvedAt, -25),
      updatedAt:
        household.request.stopStatus === "delivered"
          ? addMinutes(household.request.approvedAt, 190)
          : SEED_NOW,
    })
  );

  const routesSeed: NewRoute[] = [
    {
      id: "route-victoria-core",
      routeName: "Victoria core lunch run",
      areaLabel: "Fernwood to James Bay",
      serviceDate: day(TODAY),
      volunteerId: "volunteer-rosa-martinez",
      vehicleId: "vehicle-bluebird-cooler",
      startDepotId: "depot-victoria-central",
      status: "in_progress",
      plannedDriveMinutes: 36,
      plannedStopMinutes: 16,
      plannedTotalMinutes: 52,
      stopCount: 8,
      deliveredCount: 1,
      remainingCount: 7,
      capacityUtilizationPercent: 93,
      routeExplanation:
        "Prioritizes downtown high-urgency meals, keeps the stop that needs refrigeration first, and stays inside Rosa's lunch-hour window.",
      warnings: [],
      dashboardAnchorSessionId: null,
      lastActivityAt: stamp("2026-04-23T12:14:00-07:00"),
      createdAt: stamp("2026-04-23T08:52:00-07:00"),
      updatedAt: stamp("2026-04-23T12:14:00-07:00"),
    },
    {
      id: "route-esquimalt-loop",
      routeName: "Esquimalt shoreline loop",
      areaLabel: "Vic West and Esquimalt",
      serviceDate: day(TODAY),
      volunteerId: "volunteer-calvin-leung",
      vehicleId: "vehicle-harbour-van",
      startDepotId: "depot-victoria-central",
      status: "in_progress",
      plannedDriveMinutes: 75,
      plannedStopMinutes: 6,
      plannedTotalMinutes: 81,
      stopCount: 3,
      deliveredCount: 1,
      remainingCount: 2,
      capacityUtilizationPercent: 75,
      routeExplanation:
        "Pairs one chilled stop with two close shoreline drop-offs so Calvin can cover the west side in a single sweep.",
      warnings: ["Cooler tote needs a quick scan before the final handoff."],
      dashboardAnchorSessionId: null,
      lastActivityAt: stamp("2026-04-23T12:09:00-07:00"),
      createdAt: stamp("2026-04-23T08:50:00-07:00"),
      updatedAt: stamp("2026-04-23T12:09:00-07:00"),
    },
    {
      id: "route-oak-bay-support",
      routeName: "Oak Bay support run",
      areaLabel: "Jubilee and Oak Bay",
      serviceDate: day(TODAY),
      volunteerId: "volunteer-amira-patel",
      vehicleId: "vehicle-oak-bay-lift",
      startDepotId: "depot-victoria-central",
      status: "approved",
      plannedDriveMinutes: 95,
      plannedStopMinutes: 8,
      plannedTotalMinutes: 103,
      stopCount: 4,
      deliveredCount: 0,
      remainingCount: 4,
      capacityUtilizationPercent: 78,
      routeExplanation:
        "Leaves room for one more Eastside stop while keeping Amira available for lift-assisted requests if they clear.",
      warnings: [],
      lastActivityAt: stamp("2026-04-23T11:03:00-07:00"),
      createdAt: stamp("2026-04-23T09:18:00-07:00"),
      updatedAt: stamp("2026-04-23T11:03:00-07:00"),
    },
    {
      id: "route-peninsula-run",
      routeName: "Peninsula lunch handoff",
      areaLabel: "Saanich satellite to Sidney",
      serviceDate: day(TODAY),
      volunteerId: "volunteer-owen-mercier",
      vehicleId: "vehicle-peninsula-wagon",
      startDepotId: "depot-saanich-satellite",
      status: "approved",
      plannedDriveMinutes: 109,
      plannedStopMinutes: 16,
      plannedTotalMinutes: 125,
      stopCount: 8,
      deliveredCount: 0,
      remainingCount: 8,
      capacityUtilizationPercent: 96,
      routeExplanation:
        "Keeps the cooler load light and protects time for a same-area pickup if another peninsula request is approved overnight.",
      warnings: [],
      lastActivityAt: stamp("2026-04-23T10:57:00-07:00"),
      createdAt: stamp("2026-04-23T09:11:00-07:00"),
      updatedAt: stamp("2026-04-23T10:57:00-07:00"),
    },
    {
      id: "route-west-shore-link",
      routeName: "West Shore link",
      areaLabel: "Langford to Colwood",
      serviceDate: day(TOMORROW),
      volunteerId: "volunteer-talia-brooks",
      vehicleId: "vehicle-westshore-link",
      startDepotId: "depot-saanich-satellite",
      status: "planned",
      plannedDriveMinutes: 66,
      plannedStopMinutes: 2,
      plannedTotalMinutes: 68,
      stopCount: 1,
      deliveredCount: 0,
      remainingCount: 1,
      capacityUtilizationPercent: 60,
      routeExplanation:
        "Starts with a compact Colwood hamper and keeps time open for one compatible westbound add-on once constraints clear.",
      warnings: ["One lift-assisted West Shore request is still held back."],
      lastActivityAt: stamp("2026-04-23T10:33:00-07:00"),
      createdAt: stamp("2026-04-23T09:24:00-07:00"),
      updatedAt: stamp("2026-04-23T10:33:00-07:00"),
    },
  ];

  const routeStopDefinitions = householdSeeds
    .filter((household) => household.request.routeId && household.request.eta)
    .map((household) => ({
      household,
      stopId: `stop-${household.request.id}`,
    }));

  const routeStopsSeed: NewRouteStop[] = routeStopDefinitions.map(
    ({ household, stopId }) => ({
      id: stopId,
      routeId: household.request.routeId!,
      requestId: household.request.id,
      clientId: household.id,
      sequence: household.request.assignedStopSequence!,
      latitude: household.latitude,
      longitude: household.longitude,
      addressLine: household.addressLine1,
      eta: household.request.eta!,
      mealSummary: household.request.mealPlan
        .map(({ mealId, quantity }) => {
          const meal = deliverableMealsSeed.find(
            (entry) => entry.id === mealId
          );
          return `${quantity} ${meal?.name ?? mealId}`;
        })
        .join(", "),
      itemSummary: household.request.mealPlan
        .map(({ mealId, quantity }) => {
          const meal = deliverableMealsSeed.find(
            (entry) => entry.id === mealId
          );
          return `${quantity} ${meal?.unitLabel ?? "item"}`;
        })
        .join(", "),
      accessSummary:
        household.accessNotes ?? household.notes ?? "Standard door handoff.",
      originalMessageExcerpt: household.request.originalMessageExcerpt,
      dueBucketOrigin: household.request.dueBucket,
      status:
        household.request.stopStatus === "delivered"
          ? "delivered"
          : household.request.stopStatus === "ready"
            ? "ready"
            : "planned",
      deliveredAt:
        household.request.stopStatus === "delivered"
          ? addMinutes(household.request.eta!, 8)
          : undefined,
      notes: household.request.stopNotes,
      createdAt: addMinutes(household.request.approvedAt, 20),
      updatedAt:
        household.request.stopStatus === "delivered"
          ? addMinutes(household.request.eta!, 8)
          : SEED_NOW,
    })
  );

  const routeStopMealItemsSeed: NewRouteStopMealItem[] =
    routeStopDefinitions.flatMap(({ household, stopId }) =>
      household.request.mealPlan.map(({ mealId, quantity }) => {
        const meal = deliverableMealsSeed.find((entry) => entry.id === mealId)!;

        return {
          id: `${stopId}-${mealId}`,
          routeStopId: stopId,
          mealId,
          mealNameSnapshot: meal.name,
          quantity,
          dietaryTags: meal.dietaryTags,
          allergenFlags: meal.allergenFlags,
          refrigerated: meal.refrigerated,
          createdAt: addMinutes(household.request.approvedAt, 20),
          updatedAt: SEED_NOW,
        };
      })
    );

  const driverSessionsSeed: NewDriverSession[] = [];

  return {
    depots: depotsSeed,
    intakeMessages: intakeMessagesSeed,
    intakeDrafts: intakeDraftsSeed,
    clients: clientsSeed,
    volunteers: volunteersSeed,
    volunteerAvailability: volunteerAvailabilitySeed,
    vehicles: vehiclesSeed,
    deliveryRequests: deliveryRequestsSeed,
    deliverableMeals: deliverableMealsSeed,
    ingredientItems: ingredientItemsSeed,
    routes: routesSeed,
    routeStops: routeStopsSeed,
    routeStopMealItems: routeStopMealItemsSeed,
    driverSessions: driverSessionsSeed,
  };
}

export const seedMetadata = {
  seededAt: SEED_NOW,
  baseDates: {
    today: TODAY,
    tomorrow: TOMORROW,
    later: LATER,
  },
} as const;
